### ISSUE TITLE
https://scontent.fosl3-2.fna.fbcdn.net/v/t1.15752-9/72642019_2157086557925713_5150084353941831680_n.png?_nc_cat=104&_nc_oc=AQk6IGsJg9Iv5W_WhJ26bgKIC9be6MhPSClJ78qkNdT-6lH4E7pdbMqRW_L0hDbrTq898f8-w3lefctwesCgvZY6&_nc_ht=scontent.fosl3-2.fna&oh=b4d40cd9c341751c51154241de1d750f&oe=5E6065EB

### ISSUE THREAD

**Issue by markusranda** [Team-Cryptofile/Cryptofile-Server#2]
https://scontent.fosl3-2.fna.fbcdn.net/v/t1.15752-9/72642019_2157086557925713_5150084353941831680_n.png?_nc_cat=104&_nc_oc=AQk6IGsJg9Iv5W_WhJ26bgKIC9be6MhPSClJ78qkNdT-6lH4E7pdbMqRW_L0hDbrTq898f8-w3lefctwesCgvZY6&_nc_ht=scontent.fosl3-2.fna&oh=b4d40cd9c341751c51154241de1d750f&oe=5E6065EB

**Comment by frodekp** [comment]
Thank you for your suggestion @markusranda.
